### PR TITLE
Feature: some string functions, update progress

### PR DESCRIPTION
**Pull request by LyndonFan**
- implement and test
  - remove_all_whitespace
  - remove_non_word_characters
- update README home page by using `[x]` (replacing `[ ]`) to show we've completed a function

### CODE REVIEW

**Comment by TomBurdge** [comment]
looks good, but main won't have an `expression.rs` file anymore when this goes in:
https://github.com/TomBurdge/harley/pull/11
Do you think `spaces` is a fine name for these function types? Probably `space` is better convention...

**Comment by LyndonFan** [comment]
Don't really have a preference, so inclined to go with `spaces` for now. We can refactor / clean up once it's more populated

**Comment by TomBurdge** [comment]
Ok! The null/blank PR is merged so you should be able to merge after resolving the conflicts + v minor branch refactor.

**Comment by LyndonFan** [comment]
Great! I've merged main back into this feature branch so it should be ready

**Review by TomBurdge — APPROVED** [review]

**Pull request merged**
